name: Main

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update secret
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          arguments: githubSecretsManagerTask
  readSecret:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Read secret
        uses: gradle/gradle-build-action@v2
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
        with:
          arguments: githubSecretsRead