name: Main

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: curl
        run: |
      - name: Fetch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Execute
        uses: gradle/gradle-build-action@v2
        with:
          arguments: githubSecretsManagerTask