name: Main

on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          SECRET="secret"
          echo "secret=$SECRET" >> $GITHUB_ENV
      - run: |
          echo "$SECRET"