name: Main

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: curl
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --url https://api.github.com/repos/devshiro/gradle-github/actions/secrets/public-key
#      - name: Fetch
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Execute
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: githubSecretsManagerTask