name: Main

on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./gradlew produce
      - run: |
          SECRET=$(cat build/secret.json)
          echo "::add-mask::$SECRET"
          echo "json=$SECRET" >> $GITHUB_ENV
          ls -l $GITHUB_ENV
      - run: |
          echo secret is $json