name: Main

on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          SECRET="{\"asd\":\"value\"}"
          echo "::add-mask::$SECRET"
          echo "json=$SECRET" >> $GITHUB_ENV
      - run: |
          echo secret is $JSON