name: Main

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Execute
        uses: gradle/gradle-build-action@v2
        with:
          arguments: githubSecretsManagerTask