name: Main

on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.secret }}
    steps:
      - id: step1
        run: |
          SECRET="secret"
          echo "::add-mask::$SECRET"
          echo "secret=$SECRET" >> "GITHUB_ENV"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "::add-mask::$SECRET"
          echo "$SECRET"