name: Main

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.produce_config.outputs.json }}
    steps:
      - name: Fetch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update secret
        id: produce_config
        run: echo "json={\"asd\":\"test\"}" >> "$GITHUB_OUTPUT"
      - name: Use secret
        env:
          JSON: ${{ needs.main.outputs.json }}
        run: echo "json value $JSON"